service: my-python-lambda

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11
  region: us-east-1

plugins:
  - serverless-python-requirements

functions:
  create_account:
    handler: main.lambda_create_account
    events:
      - httpApi:
          path: accounts/create
          method: post

  get_account:
    handler: main.lambda_get_account
    events:
      - httpApi:
          path: accounts/{accountId}
          method: get

  update_status:
    handler: main.lambda_update_status
    events:
      - httpApi:
          path: accounts/update_status
          method: patch

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true
    layer: false
    useStaticCache: true
    noDeploy: []
